# Dockerfile específico para el servicio API
FROM node:18-alpine

# Establecer directorio de trabajo
WORKDIR /usr/src/app

# Copiar archivos de dependencias
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto de los archivos
COPY . .

# Exponer el puerto para la API
EXPOSE 3001

# Definir variable de entorno
ENV NODE_ENV development

# Comando por defecto (será sobreescrito por docker-compose)
CMD ["node", "src/api/index.js"]
