# Dockerfile específico para el servicio Broker MQTT
FROM node:18-alpine

# Establecer directorio de trabajo
WORKDIR /usr/src/app

# Copiar archivos de dependencias
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto de los archivos
COPY . .

# Definir variable de entorno
ENV NODE_ENV development

# Comando para ejecutar el broker
CMD ["node", "src/broker/mqttClient.js"]
